### ISSUE TITLE
Multiple RCE vulnerabilities exploitable through MitM attacks

### ISSUE THREAD

**Issue by eligrey** [fireeye/commando-vm#10]
Details here: <https://www.reddit.com/r/netsec/comments/b6r415/fireeye_introduces_commando_vm_windows_offensive/ejol6k8/>

**Comment by htnhan** [comment]
@eligrey  There are two issues here:

1. Currently Commando uses HTTP instead of HTTPS, which is vulnerable to MitM or code injection. We have a PR #1 to fix this issue.

2. Commando VM uses BoxStarter and chocolatey to help manage our packages. Similar to this issue on FLARE VM: https://github.com/fireeye/flare-vm/issues/108, Commando VM also have issues installing BoxStarter. Since we plan for Commando VM to be used as a VM, we decided to make a compromise and trust the cert temporarily simply to get BoxStarter installed. However, we are investigating a permanent solution for Commando VM.
