### ISSUE TITLE
BUG: Install can not find fireeye sources

### ISSUE THREAD

**Issue by notrednamc** [fireeye/commando-vm#114]
I have several tools/packages that will not install because the fireeye source is not available or missing. Any fix/advice/way forward?

**Comment by day1player** [comment]
Can you post your error? Are you able to browse to https://www.myget.org?

**Comment by jochu38** [comment]
i had the same error as well when i tried to run the install script a 2nd time to make sure everything installed properly.   Ill post my log of  what came up in powershell.  Still learning so my workflow might be wrong.  Everything went well until the first error at PoshC2, then Spiderfoot, wfuzz,  Watson, Pwnedpasswords, openvpn, then the very end after win10config.fireeye i tried to run just the win10config.fireeye file and recieved the myget error.
[chocolatey.log](https://github.com/fireeye/commando-vm/files/4043396/chocolatey.log).  I looked around and saw some of the errors were due to the installer looking for a different url address, like for the Dnspy tool

**Comment by day1player** [comment]
Cool, would appreciate the logs. The config package is pretty important, so it would be good if you could get it installed 👍

**Comment by Donovoi** [comment]
[choco.summary.log](https://github.com/fireeye/commando-vm/files/4080456/choco.summary.log)
[chocolatey.log](https://github.com/fireeye/commando-vm/files/4080457/chocolatey.log)
Hi Same error here. 

Please see attached logs

**Comment by goremageddon** [comment]
Directory: C:\ProgramData\chocolatey\lib-bad


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/27/2020   7:58 PM                commandovm.win10.config.fireeye
d-----        1/27/2020   7:44 PM                dnspy.flare
d-----        1/27/2020   7:48 PM                metasploit.flare
d-----        1/27/2020   7:51 PM                PoshC2.fireeye
d-----        1/27/2020   7:47 PM                proxycap.fireeye
d-----        1/27/2020   7:43 PM                python3
d-----        1/27/2020   7:55 PM                Watson.fireeye
d-----        1/27/2020   7:55 PM                wfuzz.fireeye
d-----        1/27/2020   7:46 PM                x64dbg.fireeye

**Comment by day1player** [comment]
Please see #122
