### ISSUE TITLE
Updating 'python3 3.7.2' to 'python3 3.8.5.20200721' failed

### ISSUE THREAD

**Issue by pprpst** [fireeye/commando-vm#156]
**Describe the bug and expected behavior**
Updating 'python3 3.7.2' to 'python3 3.8.5.20200721' failed

**To Reproduce**
run  "cup all" command in CMDer

**Screenshots**

![image](https://user-images.githubusercontent.com/6819167/88295414-af6a6880-ccfd-11ea-95de-0fd7f4bb144c.png)

**Version**
 - OS: Windows 10 Enterprise ,  64 bit

**Additional context**
`Failures
 python3 (exited 1) - python3 not upgraded. An error occurred during installation:
 Updating 'python3 3.7.2' to 'python3 3.8.5.20200721' failed. Unable to find a version of 'libraries.python2.fireeye' that is compatible with 'python3 3.8.5.20200721'.
 cmder (exited 2) - Error while running 'C:\ProgramData\chocolatey\lib\Cmder\tools\chocolateyInstall.ps1'.
 See log for details.
 dnspy.flare (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\dnspy.flare\tools\chocolateyInstall.ps1'.
 See log for details.
 syspin (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\syspin\tools\chocolateyInstall.ps1'.
 See log for details.`

**Comment by day1player** [comment]
@pprpst This was an unfortunate bug in some earlier versions of Commando. I have since removed the `libraries.python2.fireeye` dependency from all of the Commando packages, however, some FLARE VM packages still require it so it is going to stick around. 

In the mean time, if you need Python 3.8 you should be able to update manually with `cup -y -f python3` and it should not break any of the other packages.

Also, unless you upgrade (reinstall Commando) to the current version of Commando (2020.2) this annoyance might continue to plague you 😄

**Comment by pprpst** [comment]
TX ! ... will reinstall all. keep up good work.
