### ISSUE TITLE
Install Location Change

### ISSUE THREAD

**Issue by PjAwasthi09** [fireeye/commando-vm#165]
**Is it possible to install it on any other Drive than C because the existing installation of Windows has left me with 44 GB of space. I'd like to install it on my Main OS not VM plus also on D Drive**
**Any ideas as to how ?**

**Comment by day1player** [comment]
@PjAwasthi09 I think the best option would be to do a custom install and use the [Lite profile](https://github.com/fireeye/commando-vm/tree/master/Profiles), and then before you install go into the profile file and change the [`RAW_TOOLS_DIR`](https://github.com/fireeye/commando-vm/blob/4f04875d1cb349d7a0f365d54ff6c354ca311925/Profiles/lite.json#L6) variable to be something on the D: drive and that would install a good amount of tools onto D instead of C.

For what its worth, the recommended disk sizes _include_ the size of windows. If you look at the profiles table in the link above, the Default profile will take 40 GB of space _with_ windows.. So we install about 20 GB of tools.. If you have 44 GB left, you should be good. I would recommend also if you are going to be installing onto bare metal that you use the Nested V profile because that will install Kali and Docker for you. Also, I would recommend going through the tools in the json file and removing things you dont think are necessary for what you want to do (you can always install them later)

**Comment by PjAwasthi09** [comment]
Ok Thanks for the reply 😊
