### ISSUE TITLE
Change recommended disk size in README.md

### ISSUE THREAD

**Issue by sdcampbell** [fireeye/commando-vm#20]
After a fresh install on a new Windows 10 Pro VM with 60GB disk, I downloaded Ghidra and couldn't unzip it due to the disk being full. Please increase the recommended disk space in the README.

**Comment by day1player** [comment]
@sdcampbell perhaps we should just say how much space the VM takes? (right around 50 GB)

We don't want to require too big of a hard drive because VMs will quickly take up all of your hard drive space, especially with snapshots. However, users should know how big the install is so they can increase if they would like.

**Comment by KINGSABRI** [comment]
@sdcampbell good point. I have the same setup now. 
What about installing the tools on another disk?

**Comment by sdcampbell** [comment]
@day1player I would recommend editing the README to say that the minimum disk space requirement is 60GB and add that 65 to 80 GB is ideal.
