### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Craftzman7** [fireeye/commando-vm#260]
The last commit was over 6 months ago and I'm not seeing responses to any issues, current windows versions aren't supported, is this project abandoned?

**Comment by day1player** [comment]
@Craftzman7 an excellent question. I am kind of a one-man band with this project. The project is absolutely not abandoned, but I have to work as a consultant and a lot of times it is hard to prioritize this project over client work. I have worked with my managers and I have some time allotted in July this year (13 months since the last commit, I know 😞). The best thing you can do to help me is open issues like this one and send messages on twitter.

Thanks for the interest in the project, hopefully you stay tuned for the July update!

**Comment by Craftzman7** [comment]
> 
> 
> @Craftzman7 an excellent question. I am kind of a one-man band with this project. The project is absolutely not abandoned, but I have to work as a consultant and a lot of times it is hard to prioritize this project over client work. I have worked with my managers and I have some time allotted in July this year (13 months since the last commit, I know 😞). The best thing you can do to help me is open issues like this one and send messages on twitter.
> 
> Thanks for the interest in the project, hopefully you stay tuned for the July update!

Thanks for responding and letting me know what's up. Good to know that the project isn't dead.
