### ISSUE TITLE
BUG impossible to open Kali..

### ISSUE THREAD

**Issue by littlestewart** [fireeye/commando-vm#267]
Hi,

im unable to open kali after installing commando.

and why this is the version 2018.3 and wsl 1 ?

the error is when opening kali-gui.exe:

![image](https://user-images.githubusercontent.com/71742137/128808340-93e24270-e327-4b28-a9f5-463104ffa3dd.png)

and when i open kali.exe no tools is installed !?

I really want to use this distro to deploy this during internal engagement.. but if it this to hard to deploy without problem :/

**Version**
Windows 10 Pro Activated 21H1

**Comment by day1player** [comment]
@littlestewart you might want to make sure that you have run `apt update && apt upgrade -y`. Additionally take a look at some of [Kali's metapackages](https://tools.kali.org/kali-metapackages) so you have all of the tools. I'd recommend starting with `kali-linux-default` and also `kali-desktop-xfce` as a start. If you are going in somewhere where you wont have internet connectivity you might try `kali-linux-large`. 

As for why it's 2018.3, we do not manage that chocolatey package, it is maintained by Offensive Security, and they havent updated in a while. As for WSL1 I havent found a good way to reliably auto-install WSL2 since it seems to be only supported on the newest version of windows each time (rather than 1909+)..

To be honest I havent looked at this package in a while, so if there are any more bugs please post them here :-)
