### ISSUE TITLE
Installing CommandoVM takes too much time. I think there should be something like .voa format . So that it is ready when unpacked. Overhead of existing windows installation also takes too much space. 

### ISSUE THREAD

**Issue by zeeshan1991k** [fireeye/commando-vm#59]

**Comment by zeeshan1991k** [comment]
I think there should be something like .voa format . So that it is ready when unpacked. Overhead of existing windows installation also takes too much space.

**Comment by day1player** [comment]
@zeeshan1991k I agree, it does take much longer than we initially tested, especially recently. We are currently investigating this, we believe we know where the issue lies and are hoping to have a fix in the coming releases. We are also looking at packer/vagrant as an additional method of installing/configuring Commando.

Did you mean .ova? If so, that will not be possible as we can not distribute the Windows OS.

**Comment by joeminicucci** [comment]
@day1player Any word on packer / vagrant roadmaps, i.e. is it in progress or still planned for the future?

**Comment by day1player** [comment]
@joeminicucci yes they are still on the roadmap, hopefully very soon. I have some time in June to knock out a few things and this would be a good opportunity for that. I was planning to create multiple profiles for the install as well, this way the default install will be sped up a decent amount and take much less space. I can probably take care of the profiles and the packer/vagrant options as the most glaring issue right now is time and space requirements for install.
