### ISSUE TITLE
BUG - TaskBar not modified, programs not installing

### ISSUE THREAD

**Issue by Wh0o0** [fireeye/commando-vm#74]
**Describe the bug and expected behavior**
Haven't parsed the full list of what should and should not be installed, but a few key items I know are to be included are not installed. These include Visual Studio 2017 and wfuzz. Visual Studio Code does install correctly however. On both Pro and Ent the install script is not removing/adding items to the task bar. The search bar is not being removed from the taskbar either. The attached content is from Windows 10 Enterprise. Same issues happening on Windows 10 Pro.

**To Reproduce**
1. Run .\install.ps1 -bypass on fully patched Win10 system as Admin. (Tried -Unrestricted as well, same result, as expected)
2. See taskbar not modified and programs missing

**Version**
 - OS: Win 10 Pro 64bit & Win 10 Ent 64 bit

**Additional context**
First run through I had defender enabled but many programs were failing. All additional installs I set an exclusion for the root of C in defender. This seemed to solve all of the initial program install issues. No additional AV installed, no AV on host, just defender. Attached are Boxstarter and Chocolatey logs, system information, screenshot of the only failed package reported by chocolatey (by looking in the lib-bad directory), and a listing of programs installed in common locations. The attached content is from Win10 Ent.

[boxstarter.log](https://github.com/fireeye/commando-vm/files/3311185/boxstarter.log)
[chocolatey.log](https://github.com/fireeye/commando-vm/files/3311191/chocolatey.log)
[installedprogs.txt](https://github.com/fireeye/commando-vm/files/3311195/installedprogs.txt)
![sysinfo](https://user-images.githubusercontent.com/52027004/59863376-38b8aa00-934a-11e9-9fa5-095fbd02b12f.png)
![wfuzz_fails ](https://user-images.githubusercontent.com/52027004/59863395-4110e500-934a-11e9-8692-42e78ab675fd.png)

**Comment by day1player** [comment]
It sounds like the `commandovm.preconfig.win10.fireeye` package is not getting installed. This is the package that removes the search bar, disables defender, etc. 

I'm not sure why its failing.. You could do this two ways: 1. If you could, revert snapshot back to a fresh windows install and restart the install (don't worry about defender) keep an eye out for the preconfigured package to be installing, (you will see the prompt turn a teal color with yellow text and making lots of config changes) or 2. install chocolatey manually, then run the following command to force install of the preconfigured package to make sure its working: `choco install -s https://www.myget.org/F/fireeye/api/v2 commandovm.preconfig.win10.fireeye -y`

As to why VS 2017 and Wfuzz didn't install I am not too sure. Some packages unfortunately fail during the install process but then manually install just fine right after.. For example if you were to go into that `lib-bad` folder in your screen shot, all of those folder names are the same name as the packages.. So for Wfuzz you could just run `cinst wfuzz.fireeye` and it will install it.. to manually install Visual Studio you can run `cinst visualstudio2017community`

**Comment by Wh0o0** [comment]
Thanks for the quick reply.

I tried your second suggestion, manually installing chocolatey and then force installing commandovm.preconfig.win10.fireye. It seems the issue is getting the package from myget. I can connect to myget but the package is not found. See attached.

![preconf](https://user-images.githubusercontent.com/52027004/59869679-c5faff00-9348-11e9-80e5-1a8c41b39fb2.png)
![my_get](https://user-images.githubusercontent.com/52027004/59869680-c5faff00-9348-11e9-9248-c5886edd4fa3.png)

**Comment by day1player** [comment]
Oops, it’s actually `commandovm.win10.preconfig.fireeye`

**Comment by Wh0o0** [comment]
The install reports a success (as far as I can tell). The search bar is still on the taskbar however. It's possible that parts of the install (or all parts with the exception of from removing search bar) succeeded and others did not. Since the other packages are not installed that would be pinned to the taskbar it's difficult to say definitively.

I double-checked defender to see if it is disabled as this is part of that preconfig package and it does appear to be. It reports that it's "managed by your organization".

Attached is the terminal output and chocolatey log condensed to just the preconfig install.

[terminal.out.txt](https://github.com/fireeye/commando-vm/files/3311647/terminal.out.txt)
[preconf.chocolatey.txt](https://github.com/fireeye/commando-vm/files/3311643/preconf.chocolatey.txt)

**Comment by day1player** [comment]
I'll have to put a note in to update that package. It could be related to some windows updates since we first released. If you're curious, the script we use to disable all of that stuff is right here: https://github.com/Disassembler0/Win10-Initial-Setup-Script
We just use a different `default.preset` file. 

Since Defender seems ok now, feel free to run the install again (no need to revert snapshot, it should install just fine). Let me know if you run into anymore issues

**Comment by Wh0o0** [comment]
It looks like the search bar is tied to the "SearchboxTaskBarMode"

This can be changed by issuing the following:

Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" -Name "SearchboxTaskBarMode" -Type DWord -Value 0

Explanation of values:
0 - completely disable search
1 - show magnifying glass icon
2 - full search box

**Comment by day1player** [comment]
Gotcha. 

If you look at our [preset](https://github.com/fireeye/commando-vm/blob/master/commandovm.win10.preconfig.fireeye/tools/Default.preset) on line 96 I believe is the function.. It doesn't look like its set.. Which is odd because according to my latest install, we should be setting it to `1 - show magnifying glass icon`
<img width="366" alt="image" src="https://user-images.githubusercontent.com/37482972/59882132-5fdd9e80-937f-11e9-98de-aed84ca2a675.png">


Thanks for bringing it up I will investigate :-)

**Comment by pr0tean** [comment]
Hello - First off, thanks for providing Commando VM :)

On my side a few things are failing and here's where am at with troubleshooting:

- Wfuzz -- is failing due to missing the python library "libcurl" in windows - I'm not entirely sure what the easiest way is to provide this library in windows, reading about it looks like it's one of those issues that will require some thinking. I'll let you know if I come up with something.

- Elite.fireeye & covenant.fireeye -- both Elite.fireeye & covenant.fireeye are failing due to the chocolatey dependency "dotnetcore-runtime.install/2.2.5" being flagged as "Rejected" on 18th of June 2019. (https://chocolatey.org/packages/dotnetcore-runtime.install/2.2.5). 

More as an FYI, please be aware that latest Windows 10 includes Python in the Windows Store now. As a result, running "python" on will currently pop open the windows store. The $PATH variable for this either needs to be removed (or moved further towards the end of the $PATH list). IMHO this is bad practise from Microsoft but it is what it is for now.

**Comment by day1player** [comment]
@pr0tean thank you, I will create some new issues and tag you in them

**Comment by day1player** [comment]
@Wh0o0 Are you still having issues? We are currently investigating issues with Windows Defender Tamper Protection. I'm wondering if this might be related. 

Can you check your registry settings for `HKLM\SOFTWARE\Microsoft\Windows Defender\Features`? If there is a `TamperProtection` value you there please let me know what it is set to.

**Comment by Wh0o0** [comment]
@day1player I have been using the same install since you had me run the preconfig standalone as the setup has been working great. I have added the few tools that I noticed didn't install initially, Visual Studio and wfuzz, and the system has been working fine. I too ran into the python issue but modified the environment to have it execute in C:\Python27 so that issue was resolved.

I checked that registry key and it has Tamper Protection set to 0

```
TamperProtection : 0
PSPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Features
PSParentPath     : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender
PSChildName      : Features
PSDrive          : HKLM
PSProvider       : Microsoft.PowerShell.Core\Registry
```

If you want me to run another install or check any other settings, just let me know.

**Comment by day1player** [comment]
closing as issue appears to be resolved.
