### ISSUE TITLE
Many developer tools installed but not listed under Tools > Dev Tools

### ISSUE THREAD

**Issue by shikiko** [fireeye/commando-vm#79]
![CommandoVM-2019-06-29-00-37-16](https://user-images.githubusercontent.com/14848134/60357380-15ef5b00-9a06-11e9-9250-44aec7672fca.png)

Was trying to use python and had to go to the actual folder ( C:\python27) to use it. Environment not set either so unable to use python in cmd. Went to check the tools folder and no shortcut was shown for the installed tools. Typing python in cmd leads to the windows store

**Comment by htnhan** [comment]
@shikiko Regarding python issue, we include both Python2.7 and Python3.7. I strongly recommend trying the python launcher instead of running python directly. To execute python27, run:

```
py -2
```

To run pip for python3.7, run:

```
py -3 -m pip install superpackage
```

Regarding the dev tools, which tools do you think need to be under development tools?

**Comment by pr0tean** [comment]
FYI this sounds like it's partly related to: https://github.com/fireeye/commando-vm/issues/77

**Comment by day1player** [comment]
@pr0tean were you able to get it resolved?

**Comment by pr0tean** [comment]
@day1player python PATH issue now seems to be fixed on fresh installation! 👍
