### ISSUE TITLE
BUG: Upgrading to CommandoVM 2 - Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by gnomefish** [fireeye/commando-vm#91]
**Describe the bug and expected behavior**

Upgrading Commando VM 1 to 2 gives this error on most packages

AD-control-paths.fireeye v1.0.0.3
ad-control-paths.fireeye package files upgrade completed. Performing other installation steps.
ERROR: Cannot bind argument to parameter 'Path' because it is null.
The upgrade of ad-control-paths.fireeye was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\AD-control-paths.fireeye\Tools\chocolateyInstall.ps1'.
 See log for details.

**To Reproduce**
cup all

**Screenshots**

**Version**
 - OS: WIN10

**Additional context**

**Comment by ralphyz** [comment]
Same behavior on Win10 Enterprise

**Comment by MalwareMechanic** [comment]
Hey there! Apologies for the upgrade issues. Can you try a few things for us?

1. Set the following env var:
`$toolListDirShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk"
[Environment]::SetEnvironmentVariable("TOOL_LIST_SHORTCUT", $toolListDirShortcut, 2)`
2. Manually install common.fireeye via `cinst common.fireeye`
3. Instead of `cup all`, upgrade via: `choco upgrade commandovm.win10.installer.fireeye`

Please let us know how this goes

**Comment by ncoppersmith-r7** [comment]
If I run the following: 
> $toolListDirShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk" [Environment]::SetEnvironmentVariable("TOOL_LIST_SHORTCUT", $toolListDirShortcut, 2)

Throws the following error:

> Join-Path : A positional parameter cannot be found that accepts argument '[Environment]::SetEnvironmentVariable'.
At line:1 char:24
 ... rShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk" [Environ ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (:) [Join-Path], ParameterBindingException
     FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

Then running `choco upgrade commandovm.win10.installer.fireeye` gives the same error running `cup all` does when installing packages

> firefox.fireeye package files upgrade completed. Performing other installation steps. ERROR: Cannot bind argument to parameter 'Path' because it is null. The upgrade of firefox.fireeye was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\firefox.fireeye\tools\chocolateyInstall.ps1'.  See log for details.  Chocolatey upgraded 0/1 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Failures  - firefox.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\firefox.fireeye\tools\chocolateyInstall.ps1'.  See log for details.

**Comment by ralphyz** [comment]
@ncoppersmith-r7 There are two separate commands that appear as one long command.
1) `$toolListDirShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk" `
2) `[Environment]::SetEnvironmentVariable("TOOL_LIST_SHORTCUT", $toolListDirShortcut, 2)`

@MalwareMechanic I get an error when I run the second command (using --force):

```
Failures
- common.fireeye - common.fireeye not installed. The package was not found with the source(s) listed.
Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,  the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more assistance.
```

**Comment by ncoppersmith-r7** [comment]
Setting the `$toolListDirShortcut` & `[Environment]` does not appear to fix the issue. `cinst common.fireeye` is at version 3

COMMANDO  8/8/2019 2:45:24 PM
PS C:\WINDOWS\system32 > $toolListDirShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk"
COMMANDO 8/8/2019 2:53:18 PM
PS C:\WINDOWS\system32 > [Environment]::SetEnvironmentVariable("TOOL_LIST_SHORTCUT", $toolListDirShortcut, 2)
COMMANDO 8/8/2019 2:53:41 PM
PS C:\WINDOWS\system32 > choco upgrade commandovm.win10.installer.fireeye
Chocolatey v0.10.15
[Pending] Removing incomplete install for 'commandovm.win10.installer.fireeye'
Upgrading the following packages:
commandovm.win10.installer.fireeye
By upgrading you accept licenses for the packages.
commandovm.win10.installer.fireeye is not installed. Installing...

commandovm.win10.installer.fireeye v2.0
commandovm.win10.installer.fireeye package files upgrade completed. Performing other installation steps.
WARNING: The names of some imported commands from the module 'Boxstarter.Common' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Boxstarter: Setting PowerShell execution context to Unrestricted
Boxstarter: Setting Windows Explorer options...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Microsoft Update is already disabled, no action will be taken.
GameBar Tips have been disabled.
Initializing chocolatey
Chocolatey v0.10.15
Nothing to change. Config already set.
Chocolatey v0.10.15
Nothing to change. Config already set.
Chocolatey v0.10.15
Nothing to change. Config already set.
C:\Users\XDP4\AppData\Local\ChocoCache
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm dotnet4.6.2 is installed properly
WARNING: [!] Executing: iex choco upgrade dotnet4.6.2 --cacheLocation C:\Users\XDP4\AppData\Local\ChocoCache -y
Chocolatey v0.10.15 Upgrading the following packages: dotnet4.6.2 By upgrading you accept licenses for the packages. dotnet4.6.2 v4.6.01590.20190226 is the latest version available based on your source(s).  Chocolatey upgraded 0/1 packages.   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Enjoy using Chocolatey? Explore more amazing features to take your experience to the next level at  https://chocolatey.org/compare
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm dotnet4.7.2 is installed properly
WARNING: [!] Executing: iex choco upgrade dotnet4.7.2 --cacheLocation C:\Users\XDP4\AppData\Local\ChocoCache -y
Chocolatey v0.10.15 Upgrading the following packages: dotnet4.7.2 By upgrading you accept licenses for the packages. dotnet4.7.2 v4.7.2.20180712 is the latest version available based on your source(s).  Chocolatey upgraded 0/1 packages.   See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
WARNING: [!] Installing using host choco.exe! Errors are ignored. Please check to confirm cmder.fireeye is installed properly
WARNING: [!] Executing: iex choco upgrade cmder.fireeye --cacheLocation C:\Users\XDP4\AppData\Local\ChocoCache -y
Chocolatey v0.10.15 Upgrading the following packages: cmder.fireeye By upgrading you accept licenses for the packages.  You have cmder.fireeye v2019.03.14.2 installed. Version 2019.03.14.6 is available based on your source(s).  Progress: Downloading cmder.fireeye 2019.03.14.6... 59% Progress: Downloading cmder.fireeye 2019.03.14.6... 100%  cmder.fireeye v2019.03.14.6 cmder.fireeye package files upgrade completed. Performing other installation steps. ERROR: Cannot bind argument to parameter 'Path' because it is null. The upgrade of cmder.fireeye was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.  See log for details.  Chocolatey upgraded 0/1 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Failures  - cmder.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.  See log for details.

**Comment by tonykarre** [comment]
What does the ChocolatelyScriptRunner do?  as in:
2019-08-12 21:02:02,342 1964 [DEBUG] - Running 'ChocolateyScriptRunner' for keepass.fireeye v2019.03.14.3 with packageScript 'C:\ProgramData\chocolatey\lib\keepass.fireeye\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\keepass.fireeye', installArguments: '', packageParameters: '',
2019-08-12 21:02:02,373 1964 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\keepass.fireeye\tools\chocolateyInstall.ps1'
2019-08-12 21:02:02,405 1964 [ERROR] - ERROR: Cannot bind argument to parameter 'Path' because it is null.


If you step through the xxxinstall.ps1 scripts manually in powershell ISE, all of the environment variables are fine and "$path" is fine.  If this chocolatelyscriptrunner is launching the powershell script, I suspect that it is losing (or never had access to) the TOOL_LIST_SHORTCUT environment variable.  For instance, if you manually corrupt the creation of $path like this, then you achieve the same effect:

PS C:\Users\tonyk> $path = Join-Path ${Env:TOOL_LIST_SHORTCUTxxx} 'Utilities'
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:19
+ $path = Join-Path ${Env:TOOL_LIST_SHORTCUTxxx} 'Utilities'
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

**Comment by tonykarre** [comment]
@MalwareMechanic  I think that the trouble is with environment variable TOOL_LIST_DIR.

I added the following to chocolateyscriptrunner:

```
$processEnvironment = [System.Environment]::GetEnvironmentVariables("Process");
# Enumerate environmental variables
foreach($tempvariable in $processEnvironment.GetEnumerator() | Sort-Object Name) {
  Write-Host "$($tempvariable.Key)`t$($tempvariable.Value)"
}
```

Here are the environment variables seen at the time.

```
<snip>
SystemRoot      C:\Windows
TEMP    C:\Users\tonyk\AppData\Local\Temp
TMP     C:\Users\tonyk\AppData\Local\Temp
**TOOL_LIST_SHORTCUT**      C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tool List
USER_DOMAIN     COMMANDO
<snip>
```

Now looking at chocolateyinstall for ADACLScanner, I see this:

```
$name = "ADACLScanner"
$path = Join-Path ${Env:TOOL_LIST_DIR} "Information Gathering"
```

Same for ADAPE-Script.

So somehow we are losing the TOOL_LIST_DIR environment variable.

**Comment by htnhan** [comment]
This is likely an issue with the `TOOL_LIST_DIR` environment variable. Please also set that environment variable by running the following command:
- `[Environment]::SetEnvironmentVariable("TOOL_LIST_DIR", "%ProgramData%/Microsoft\Windows\Start Menu\Programs\Tools")`

@tonykarre As of version `1.3`, we sets the `TOOL_LIST_SHORTCUT` environment variable in `chocolateyInstall.ps1` of the `commandovm.win10.installer.fireeye` package. Moving to version `2.0`, we refactor a lot of our code into a `common.fireeye` package. It's `common.fireeye` package that sets and saves many of the environment variables. `install.ps1` only sets these environment variables to "seed" `common.fireeye` if you provide the `-profile_file` flag to pass a customize the install with `profile.json`

**Comment by ncoppersmith-r7** [comment]
Updating the environment doesn't appear to resolve the path issue:

> $toolListDirShortcut = Join-Path ${Env:UserProfile} "Desktop\Tools.lnk"
[Environment]::SetEnvironmentVariable("TOOL_LIST_SHORTCUT", $toolListDirShortcut, 2)
[Environment]::SetEnvironmentVariable("TOOL_LIST_DIR", "%ProgramData%/Microsoft\Windows\Start Menu\Programs\Tools")

Then executing **choco upgrade commandovm.win10.installer.fireeye** has the following in the log:

> 2019-08-14 14:33:40,678 5936 [DEBUG] - ---------------------------Script Execution---------------------------
2019-08-14 14:33:40,678 5936 [DEBUG] - Running 'ChocolateyScriptRunner' for cmder.fireeye v2019.03.14.6 with packageScript 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\cmder.fireeye', installArguments: '', packageParameters: '',
2019-08-14 14:33:40,678 5936 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'
2019-08-14 14:33:40,694 5936 [ERROR] - ERROR: Cannot bind argument to parameter 'Path' because it is null.
2019-08-14 14:33:40,818 5936 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2019-08-14 14:33:40,818 5936 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2019-08-14 14:33:40,865 5936 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
2019-08-14 14:33:40,928 5936 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\cmder.fireeye'
2019-08-14 14:33:40,928 5936 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\cmder.fireeye\cmder.fireeye.nupkg'
  with checksum '1A4B27DCA36B8E62138B5B10716C83FD'
2019-08-14 14:33:40,928 5936 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\cmder.fireeye\cmder.fireeye.nuspec'
  with checksum 'D41888FB173F6D62D37F2F81C8360013'
2019-08-14 14:33:40,928 5936 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'
  with checksum 'FA9DECA0B76C9581436208227C1AA7B1'
2019-08-14 14:33:40,928 5936 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyUninstall.ps1'
  with checksum 'DC549A7BE1C20671A24497A6543C6E5E'
2019-08-14 14:33:40,943 5936 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\cmder.fireeye.2019.03.14.6\.arguments".
2019-08-14 14:33:40,943 5936 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\cmder.fireeye.2019.03.14.6\.extra".
2019-08-14 14:33:40,943 5936 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\cmder.fireeye.2019.03.14.6\.version".
2019-08-14 14:33:40,943 5936 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\cmder.fireeye.2019.03.14.6\.sxs".
2019-08-14 14:33:40,943 5936 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\cmder.fireeye.2019.03.14.6\.pin".
2019-08-14 14:33:40,959 5936 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\cmder.fireeye".
2019-08-14 14:33:40,959 5936 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2019-08-14 14:33:40,959 5936 [ERROR] - The upgrade of cmder.fireeye was NOT successful.
2019-08-14 14:33:40,959 5936 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.
2019-08-14 14:33:40,974 5936 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\cmder.fireeye'
 to 'C:\ProgramData\chocolatey\lib-bad\cmder.fireeye'
2019-08-14 14:33:42,996 5936 [DEBUG] - Attempting rollback
2019-08-14 14:33:42,996 5936 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\cmder.fireeye'
 to 'C:\ProgramData\chocolatey\lib\cmder.fireeye'
2019-08-14 14:33:45,006 5936 [DEBUG] - Attempting to delete file "C:\Users\XDP4\AppData\Local\NuGet\Cache\cmder.fireeye.2019.03.14.6.nupkg".
2019-08-14 14:33:45,006 5936 [WARN ] - 
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-08-14 14:33:45,006 5936 [INFO ] - 
2019-08-14 14:33:45,006 5936 [ERROR] - Failures
2019-08-14 14:33:45,022 5936 [ERROR] -  - cmder.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by htnhan** [comment]
I'm sorry, the command should be:
- `[Environment]::SetEnvironmentVariable("TOOL_LIST_DIR", "%ProgramData%/Microsoft\Windows\Start Menu\Programs\Tools", 2)`

instead (notice number 2 and the end). Without it, you only set the environment variable for the current session. After setting `TOOL_LIST_DIR`, please also reboot/login and logout and confirm that `${Env:TOOL_LIST_DIR}` points to the right directory.

**Comment by ncoppersmith-r7** [comment]
Took me a minute to realize that one of the slashes in the command **[Environment]::SetEnvironmentVariable("TOOL_LIST_DIR", "%ProgramData%/Microsoft\Windows\Start Menu\Programs\Tools", 2)** is backwards, but even after fixing, logging out/logging in and checking it still fails.  One of the reasons I think is on my system the correct path is actually _C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tool List_.

That doesn't seem to resolve the issue though, as I still receive the following executing  **choco upgrade commandovm.win10.installer.fireeye**

>  ERROR: Cannot bind argument to parameter 'Path' because it is null. The upgrade of cmder.fireeye was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.  See log for details.  Chocolatey upgraded 0/1 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Failures  - cmder.fireeye (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\cmder.fireeye\tools\chocolateyInstall.ps1'.  See log for details.

Current variables are as follows:
echo ${Env:TOOL_LIST_DIR}
**C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Tool List**
echo ${Env:TOOL_LIST_SHORTCUT}
**C:\Users\XDP4\Desktop\Tools.lnk**

**Comment by htnhan** [comment]
@ncoppersmith-r7 The slash should be OK. I think Powershell automatically converts it to the correct slash. Would you please try two things for me:

1. Show me the output of: `Write-Host ${Env:RAW_TOOLS_DIR}`
2. By default, `RAW_TOOLS_DIR` should point to `%systemdrive%\Tools`, which should translate to `C:\Tools`. Does the directory exist on your VM?


Thank you

**Comment by ncoppersmith-r7** [comment]
It's blank:

> PS C:\WINDOWS\system32 > Write-Host ${Env:RAW_TOOLS_DIR}
>
> COMMANDO 8/14/2019 5:56:34 PM

C:\Tools does have all the tools in it.

**Comment by htnhan** [comment]
Please also set the `RAW_TOOLS_DIR` environment variable: `[Environment]:SetEnvironmentVariable("RAW_TOOLS_DIR", "%systemdrive%\Tools", 2)`, relog, and try to do the upgrade again.

**Comment by ncoppersmith-r7** [comment]
That appears to be the missing link, packages are upgrading now.
> [Environment]:SetEnvironmentVariable("RAW_TOOLS_DIR", "%systemdrive%\Tools", 2)

Needs to be **[Environment]::SetEnvironmentVariable("RAW_TOOLS_DIR", "%systemdrive%\Tools", 2)** (note the 2 colons) for anyone else following along at home.

**Comment by htnhan** [comment]
@ncoppersmith-r7  Thank you for working with us through this issue.
